name: Deploy to AWS S3 and CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build static files
        run: npm run generate

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Upload build to s3
      - name: Deploy to S3
        run: |
          aws s3 sync ./dist s3://${{ secrets.AWS_BUCKET_NAME }} --delete

      # Deploy CloudFormation Template
      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file deployment.yml \
            --stack-name dharti-nuxt-static-deployment-stack \
            --parameter-overrides S3BucketName=${{ secrets.AWS_BUCKET_NAME }} IAMuser=${{ secrets.AWS_IAM_USER }} \
            --capabilities CAPABILITY_NAMED_IAM
